# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VUser-Barracuda
version:      0.1.0
version_from: lib/VUser/Barracuda.pm
installdirs:  site
requires:
    Config::IniFiles:              0
    LWP::Simple:                   0
    VUser::Extension:              0.2.0
    VUser::ExtLib:                 0.2.0
    VUser::Meta:                   0.2.0
    VUser::ResultSet:              0.2.0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
