# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VUser-Trango
version:      0.1.0
version_from: lib/VUser/Trango/AP.pm
installdirs:  site
requires:
    Net::SNMP:                     0
    VUser::Extension:              0.3.0
    VUser::ExtHandler:             0.3.0
    VUser::ExtLib:                 0.3.0
    VUser::Log:                    0.3.0
    VUser::Meta:                   0.3.0
    VUser::ResultSet:              0.3.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
