# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VUser-Install
version:      0.1.0
version_from: lib/VUser/Install.pm
installdirs:  site
requires:
    Config::IniFiles:              0
    Cwd:                           0
    SOAP::Lite:                    0
    Socket:                        0
    Text::Template:                0
    VUser::Extension:              0
    VUser::ExtLib:                 0
    VUser::Meta:                   0
    VUser::ResultSet:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
